apiVersion: v1
kind: Namespace
metadata:
    name: image-clone-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kube-image-clone-controller
    namespace: image-clone-namespace
    labels:
        app: kube-image-clone-controller
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kube-image-clone-controller
    template:
        metadata:
            labels:
                app: kube-image-clone-controller
        spec:
            serviceAccountName: kube-image-clone-controller-service-account
            containers:
                -   image: testingnew123/kube-image-clone-controller:latest
                    name: kube-image-clone-controller-container
                    imagePullPolicy: Always

---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: kube-image-clone-controller-service-account
    namespace: image-clone-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: kube-image-clone-controller-cluster-role
    namespace: image-clone-namespace
rules:
    -   apiGroups: [ "apps" ]
        resources: [ "deployments", "daemonsets" ]
        verbs: [ "get", "list", "watch", "update" ,"patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: kube-image-clone-controller-role-binding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kube-image-clone-controller-cluster-role
subjects:
    -   kind: ServiceAccount
        name: kube-image-clone-controller-service-account
        namespace: image-clone-namespace
